padrao:
	python3 src/main.py DataBases/games.txt DataBases/outputOne.txt DataBases/outputTwo.txt DataBases/outputThree.txt DataBases/outputFour.txt

tamanhos_fixos:
	python3 src/main.py DataBases/outputOne.txt DataBases/teste.txt DataBases/outputTwo.txt DataBases/outputThree.txt DataBases/outputFour.txt

bytes_comeco:
	python3 src/main.py DataBases/outputThree.txt DataBases/teste.txt DataBases/outputTwo.txt DataBases/teste.txt DataBases/outputFour.txt

delimitador:
	python3 src/main.py DataBases/outputFour.txt DataBases/teste.txt DataBases/outputTwo.txt DataBases/teste.txt DataBases/teste.txt

clean:
	rm -rf src/__pycache__